/**
 * CSS Generation Script
 *
 * Produces distributable CSS files from token definitions.
 * Run automatically as part of the build process.
 *
 * Generated files are NOT tracked in git — they are build artifacts in dist/.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { generateCss, generateThemeCss, generateDensityCss } from "../css/index";
import { lightTheme } from "../themes/light";
import { darkTheme } from "../themes/dark";
import { comfortable, standard, compact } from "../density/index";
import { buildManifest } from "../manifest/index";
import type { SemanticTokens } from "../types/semantic";

const DIST = join(import.meta.dirname, "../../dist");
const NOTICE = "/* Generated by @kairoui/tokens — do not edit manually */\n\n";

function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}

function themeToRecord(theme: SemanticTokens): Record<string, unknown> {
  return theme as unknown as Record<string, unknown>;
}

function writeWithNotice(path: string, css: string): void {
  writeFileSync(path, NOTICE + css, "utf-8");
}

// ─── Generate theme CSS ──────────────────────────────────────────────

function generateThemeFiles(): void {
  ensureDir(join(DIST, "themes"));

  const lightResult = generateThemeCss(themeToRecord(lightTheme), "light");
  writeWithNotice(join(DIST, "themes", "light.css"), lightResult.css);

  const darkResult = generateThemeCss(themeToRecord(darkTheme), "dark");
  writeWithNotice(join(DIST, "themes", "dark.css"), darkResult.css);

  if (lightResult.errors.length > 0) {
    console.warn("Light theme CSS warnings:", lightResult.errors);
  }
  if (darkResult.errors.length > 0) {
    console.warn("Dark theme CSS warnings:", darkResult.errors);
  }
}

// ─── Generate density CSS ────────────────────────────────────────────

function generateDensityFiles(): void {
  ensureDir(join(DIST, "density"));

  const modes = [
    { name: "comfortable", tokens: comfortable },
    { name: "standard", tokens: standard },
    { name: "compact", tokens: compact },
  ] as const;

  for (const { name, tokens } of modes) {
    const result = generateDensityCss(tokens as unknown as Record<string, unknown>, name);
    writeWithNotice(join(DIST, "density", `${name}.css`), result.css);
  }
}

// ─── Generate combined tokens.css ────────────────────────────────────

function generateCombinedFile(): void {
  // Root scope with light theme as default
  const rootResult = generateCss(themeToRecord(lightTheme), { scope: ":root" });

  // Dark theme override
  const darkResult = generateThemeCss(themeToRecord(darkTheme), "dark");

  // Density overrides (only spacing + control — not full theme)
  const standardDensity = generateDensityCss(
    standard as unknown as Record<string, unknown>,
    "standard",
  );
  const compactDensity = generateDensityCss(
    compact as unknown as Record<string, unknown>,
    "compact",
  );

  const combined = [
    rootResult.css,
    "",
    darkResult.css,
    "",
    standardDensity.css,
    "",
    compactDensity.css,
  ].join("\n");

  writeWithNotice(join(DIST, "tokens.css"), combined);
}

// ─── Generate index.css (import aggregator) ──────────────────────────

function generateIndexCss(): void {
  const content = ['@import "./tokens.css";', ""].join("\n");

  writeWithNotice(join(DIST, "index.css"), content);
}

// ─── Generate JSON manifest ──────────────────────────────────────────

function generateManifestFile(): void {
  const manifest = buildManifest([
    {
      tokens: themeToRecord(lightTheme),
      options: { layer: "semantic", themes: ["light", "dark"] },
    },
    {
      tokens: comfortable as unknown as Record<string, unknown>,
      options: { layer: "density", densityApplicable: true },
    },
  ]);

  writeFileSync(join(DIST, "tokens.json"), JSON.stringify(manifest, null, 2) + "\n", "utf-8");
}

// ─── Main ────────────────────────────────────────────────────────────

export function generate(): void {
  ensureDir(DIST);
  generateThemeFiles();
  generateDensityFiles();
  generateCombinedFile();
  generateIndexCss();
  generateManifestFile();
}

// Run if executed directly
generate();
