import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const DIST = join(import.meta.dirname, "../../dist");

const EXPECTED_FILES = [
  "tokens.css",
  "index.css",
  "themes/light.css",
  "themes/dark.css",
  "density/comfortable.css",
  "density/standard.css",
  "density/compact.css",
];

function readCss(relativePath: string): string {
  return readFileSync(join(DIST, relativePath), "utf-8");
}

describe("generated CSS output", () => {
  describe("file existence", () => {
    it.each(EXPECTED_FILES)("dist/%s exists", (file) => {
      expect(existsSync(join(DIST, file))).toBe(true);
    });
  });

  describe("file content", () => {
    it("all CSS files have the generated notice", () => {
      for (const file of EXPECTED_FILES) {
        const content = readCss(file);
        expect(content).toContain("Generated by @kairoui/tokens");
      }
    });

    it("tokens.css contains :root scope", () => {
      const content = readCss("tokens.css");
      expect(content).toContain(":root {");
    });

    it("tokens.css contains dark theme override", () => {
      const content = readCss("tokens.css");
      expect(content).toContain('[data-kui-theme="dark"]');
    });

    it("tokens.css contains density overrides", () => {
      const content = readCss("tokens.css");
      expect(content).toContain('[data-kui-density="standard"]');
      expect(content).toContain('[data-kui-density="compact"]');
    });

    it("light.css uses [data-kui-theme='light'] selector", () => {
      const content = readCss("themes/light.css");
      expect(content).toContain('[data-kui-theme="light"]');
    });

    it("dark.css uses [data-kui-theme='dark'] selector", () => {
      const content = readCss("themes/dark.css");
      expect(content).toContain('[data-kui-theme="dark"]');
    });
  });

  describe("CSS validity", () => {
    it("all declarations use --kui- prefix", () => {
      const content = readCss("tokens.css");
      const varLines = content
        .split("\n")
        .filter((l) => l.includes(": ") && l.trim().startsWith("--"));
      for (const line of varLines) {
        expect(line.trim()).toMatch(/^--kui-/);
      }
    });

    it("all declarations end with semicolons", () => {
      const content = readCss("themes/light.css");
      const varLines = content.split("\n").filter((l) => l.includes("--kui-"));
      for (const line of varLines) {
        expect(line.trimEnd()).toMatch(/;$/);
      }
    });

    it("selectors have matching braces", () => {
      const content = readCss("tokens.css");
      const opens = (content.match(/\{/g) ?? []).length;
      const closes = (content.match(/\}/g) ?? []).length;
      expect(opens).toBe(closes);
      expect(opens).toBeGreaterThan(0);
    });
  });

  describe("determinism", () => {
    it("regenerating produces identical output", () => {
      // Read the file twice to confirm it's stable (file is already generated)
      const content1 = readCss("themes/light.css");
      const content2 = readCss("themes/light.css");
      expect(content1).toBe(content2);
    });

    it("variables are in a consistent order (localeCompare)", () => {
      const content = readCss("themes/light.css");
      const vars = content
        .split("\n")
        .filter((l) => l.includes("--kui-"))
        .map((l) => l.trim().split(":")[0] as string);
      const sorted = [...vars].sort((a, b) => a.localeCompare(b));
      expect(vars).toEqual(sorted);
    });
  });

  describe("density files only contain spacing/control", () => {
    it("compact.css does not contain color variables", () => {
      const content = readCss("density/compact.css");
      expect(content).not.toContain("--kui-color-");
    });

    it("standard.css contains spacing variables", () => {
      const content = readCss("density/standard.css");
      expect(content).toContain("--kui-space-");
      expect(content).toContain("--kui-control-height-");
    });
  });
});
