/**
 * KairoUI Theme Selector Strategy
 *
 * This module defines the official HTML attribute conventions for runtime theming.
 * All CSS generated by @kairoui/tokens uses these selectors.
 * All runtime theme application must use these exact attributes.
 *
 * ## Attribute Summary
 *
 * | Attribute          | Purpose                       | Values                              |
 * |--------------------|-------------------------------|-------------------------------------|
 * | data-kui-theme     | Resolved color scheme         | "light" | "dark"                    |
 * | data-kui-density   | Active density mode           | "comfortable" | "standard" | "compact" |
 *
 * ## Design Decisions
 *
 * ### data-kui-theme stores the RESOLVED mode, not the requested mode.
 *
 * When a user selects "system" mode, the attribute is set to "light" or "dark"
 * based on the OS preference — never "system". This ensures CSS selectors
 * always match a concrete color scheme without needing a third selector.
 *
 * ### No separate theme-name attribute is needed for Phase 3.
 *
 * Custom themes override token values via the same base ("light" or "dark").
 * The CSS cascade doesn't need to distinguish between "acme-light" and "light"
 * because custom overrides are applied as inline variables or additional stylesheets.
 * A `data-kui-theme-name` attribute may be added in a future phase if
 * multi-theme CSS bundles are supported.
 *
 * ### Root vs Scoped application
 *
 * - Root: attributes are set on `document.documentElement` (<html>).
 * - Scoped: attributes are set on any container element.
 * - CSS custom properties cascade naturally — scoped attributes override
 *   the parent's variables within that sub-tree.
 *
 * ### Attribute ownership
 *
 * - Only the KairoUI theme engine (or its React provider) should set these attributes.
 * - Consumers must not manually set data-kui-theme or data-kui-density and
 *   also use the theme engine, as this creates conflicts.
 * - The no-flash script is the one exception: it sets attributes before the
 *   engine initializes, and the engine reads them on init rather than overwriting.
 *
 * ### Attribute cleanup
 *
 * When a scoped provider unmounts or is destroyed, its data-kui-* attributes
 * are removed from the target element. This restores CSS cascade from the parent.
 *
 * ### Nested scope inheritance
 *
 * A nested scope only needs to set the attributes it wants to override:
 * - Setting data-kui-theme="dark" on a child inherits density from the parent.
 * - Setting data-kui-density="compact" on a child inherits theme from the parent.
 * - CSS variable cascade handles the rest — no JavaScript propagation needed.
 *
 * ### CSS specificity
 *
 * Generated CSS uses attribute selectors with equal specificity:
 *   [data-kui-theme="dark"]  — specificity (0,1,0)
 *   [data-kui-density="compact"] — specificity (0,1,0)
 *
 * Consumer overrides can use the same specificity and source order,
 * or add a class for higher specificity when needed.
 *
 * ### Shadow DOM
 *
 * CSS custom properties penetrate shadow DOM boundaries.
 * Components inside shadow DOM inherit the theme variables from their
 * host element's scope without any special attribute handling.
 * Shadow DOM components do NOT need data-kui-* attributes internally.
 *
 * ### Embedded applications
 *
 * When KairoUI is embedded in a non-KairoUI page:
 * - Set data-kui-theme and data-kui-density on the KairoUI root container,
 *   not on <html> (which belongs to the host page).
 * - The theme engine accepts a `target` option for this purpose.
 *
 * ### Server-rendered attributes
 *
 * SSR output should include data-kui-theme="light" (or the server-determined
 * default) on the <html> element. The no-flash script will patch this to the
 * user's preference before first paint. React hydration reads the patched
 * attributes, avoiding mismatch.
 */

// ─── Attribute Constants ─────────────────────────────────────────────

/** The data attribute for the resolved color scheme. */
export const THEME_ATTRIBUTE = "data-kui-theme" as const;

/** The data attribute for the active density mode. */
export const DENSITY_ATTRIBUTE = "data-kui-density" as const;

/** Dataset key for theme (camelCase version for element.dataset access). */
export const THEME_DATASET_KEY = "kuiTheme" as const;

/** Dataset key for density (camelCase version for element.dataset access). */
export const DENSITY_DATASET_KEY = "kuiDensity" as const;

// ─── Selector Helpers ────────────────────────────────────────────────

/** CSS selector that matches a specific resolved theme. */
export function themeSelector(mode: "light" | "dark"): string {
  return `[${THEME_ATTRIBUTE}="${mode}"]`;
}

/** CSS selector that matches a specific density. */
export function densitySelector(density: "comfortable" | "standard" | "compact"): string {
  return `[${DENSITY_ATTRIBUTE}="${density}"]`;
}

/** CSS selector for the default (light) root — used in :root. */
export const ROOT_THEME_SELECTOR = ":root" as const;

/** CSS selector for the dark theme scope. */
export const DARK_THEME_SELECTOR = `[${THEME_ATTRIBUTE}="dark"]` as const;

// ─── Valid Values ────────────────────────────────────────────────────

/** Valid values for data-kui-theme. Always a resolved mode, never "system". */
export const VALID_THEME_VALUES = ["light", "dark"] as const;

/** Valid values for data-kui-density. */
export const VALID_DENSITY_VALUES = ["comfortable", "standard", "compact"] as const;
